/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CompilerLangRouteImport } from './routes/compiler/$lang'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompilerLangRoute = CompilerLangRouteImport.update({
  id: '/compiler/$lang',
  path: '/compiler/$lang',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/compiler/$lang': typeof CompilerLangRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/compiler/$lang': typeof CompilerLangRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/compiler/$lang': typeof CompilerLangRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/compiler/$lang'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/compiler/$lang'
  id: '__root__' | '/' | '/compiler/$lang'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompilerLangRoute: typeof CompilerLangRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compiler/$lang': {
      id: '/compiler/$lang'
      path: '/compiler/$lang'
      fullPath: '/compiler/$lang'
      preLoaderRoute: typeof CompilerLangRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompilerLangRoute: CompilerLangRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
